name: Convert Markdown to PDF

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 変換するマークダウンに日本語が含まれる場合、日本語フォントをインストールする必要あり
      - name: Install Japanese font
        run: sudo apt install fonts-ipafont fonts-ipaexfont

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build
        run: |
          npm ci
          npm run build --if-present          

      # カレントディレクトリ配下の.mdファイルを.pdfファイルへ変換する
      - name: Convert markdown to pdf
        run: npx md-to-pdf ./*.md

      # 新規作成もしくは更新されたPDFファイルを自動コミットする
      - name: Commit output pdf files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update output pdf files
